[phases.setup]
# 移除 python3Packages.unoconv (不存在)
nixPkgs = ["jdk17", "gradle", "libreoffice", "python3", "python3Packages.weasyprint", "qpdf", "tesseract"]
# 保留apt安装方式
aptPkgs = ["libreoffice", "python3-pip", "qpdf", "tesseract-ocr", "python3-venv", "poppler-utils"]

[phases.install]
# 使用虚拟环境安装Python包
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install unoconv weasyprint opencv-python-headless",
  "ln -s /usr/bin/pdftohtml /usr/local/bin/pdftohtml || true",
  "ln -s /opt/venv/bin/unoconv /usr/local/bin/unoconv || true",
  "ln -s /opt/venv/bin/weasyprint /usr/local/bin/weasyprint || true",
  "chmod +x /opt/venv/bin/unoconv /opt/venv/bin/weasyprint",
  "echo '#!/bin/bash' > /app/start.sh",
  "echo 'export PATH=/opt/venv/bin:$PATH' >> /app/start.sh",
  "echo 'export PYTHONPATH=/usr/lib/libreoffice/program:/opt/venv/lib' >> /app/start.sh",
  "echo 'export UNO_PATH=/usr/lib/libreoffice/program' >> /app/start.sh",
  "echo 'export URE_BOOTSTRAP=file:///usr/lib/libreoffice/program/fundamentalrc' >> /app/start.sh",
  "echo '/opt/venv/bin/unoconv --listener &' >> /app/start.sh",
  "echo 'java -jar $(find build/libs/ -name \"*.jar\" ! -name \"*-plain.jar\")' >> /app/start.sh",
  "chmod +x /app/start.sh"
]

[phases.build]
cmds = ["./gradlew clean build -x check -x test"]

[start]
# 确保启动时可以访问虚拟环境中的命令
cmd = "bash /app/start.sh"