name: Release Artifacts
on: release
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate jar
      run: ./gradlew clean createJar 

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/launch4j/Stirling-PDF.exe
        asset_name: Stirling-PDF.exe
        tag: ${{ github.ref }}
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/libs/S-PDF*.jar
        asset_name: S-PDF.jar
        tag: ${{ github.ref }}


